version = 5.2.2
archive_dir = /etc/letsencrypt/archive/zyrax.bipro.tech
cert = /etc/letsencrypt/live/zyrax.bipro.tech/cert.pem
privkey = /etc/letsencrypt/live/zyrax.bipro.tech/privkey.pem
chain = /etc/letsencrypt/live/zyrax.bipro.tech/chain.pem
fullchain = /etc/letsencrypt/live/zyrax.bipro.tech/fullchain.pem
[renewalparams]
account = d15f76858a911043610eb3a3de187bda
rsa_key_size = 4096
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
zyrax.bipro.tech = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-02-01T20:26:52
